# Generated by Django 4.1.7 on 2023-04-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspublicprofile',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
