# Generated by Django 4.1.7 on 2023-04-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_profile', '0002_userspublicprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspublicprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
