# Generated by Django 4.1.7 on 2023-04-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_profile', '0003_userspublicprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspublicprofile',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
