# Generated by Django 4.1.7 on 2023-06-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_profile', '0004_userspublicprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspublicprofile',
            name='image',
            field=models.ImageField(default='images/placeholder_profile.png', null=True, upload_to='images/'),
        ),
    ]
