# Generated by Django 4.1.7 on 2023-07-12 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public_profile', '0005_alter_userspublicprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspublicprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
