# Generated by Django 4.1.7 on 2023-07-01 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_collection', '0006_alter_booktitle_cover'),
        ('book_reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('review', models.TextField(max_length=5000, null=True)),
                ('read', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_reviews.readbook')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_collection.booktitle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
