# Generated by Django 4.1.7 on 2023-07-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews', '0005_alter_bookreview_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrating',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
