# Generated by Django 4.1.7 on 2023-03-08 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('book_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal_collection.booktitle')),
            ],
            options={
                'verbose_name_plural': 'BookCopies',
            },
        ),
    ]
