# Generated by Django 4.1.7 on 2023-05-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_collection', '0003_bookcopy_owner_alter_booktitle_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktitle',
            name='cover',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
